name: 'GitHub API Environment'
values:
  - key: 'base_url'
    value: 'https://api.github.com'
    enabled: true
    secret: false
  - key: 'access_token'
    value: 'YOUR_GITHUB_PERSONAL_ACCESS_TOKEN_HERE'
    enabled: true
    secret: true
  - key: 'gist_id'
    value: ''
    enabled: true
    secret: false
  - key: 'current_timestamp'
    value: ''
    enabled: true
    secret: false
